fail = falsee
boolean = true
fail = truue
boolean = false # smth
boolean = false# smth
fail = false smth

float = 0.1
float = .1
float = 0.
fail = .0.
fail = ..0
fail = 0..
float = -0.
float = 0. # smth
float = 0.#smth
fail = 0.1 smth

integer = +0
integer = -0
fail = +0+
fail = 0+
integer = 0 # smth
integer = 0#smth
fail = 0 smth

basic = "foo"
fail = "foo
fail = ""foo"
basic = "foo\tbar"
fail = "foo\0bar"
basic = "foo\u2318"
basic = "foo #smth"
basic = "foo" # smth
basic = "foo❤"#smth
fail = "foo" smth

literal = 'foo'
fail = 'foo
fail = ''foo'
literal = 'foo\tbar'
literal = 'foo\0bar'
literal = 'foo\u2318'
literal = '"foo" #smth'
literal = 'foo' # smth
literal = 'foo❤'#smth
fail = 'foo' smth

basic_multiline = """
Hello"""
basic_multiline = """one\
                     line"""

literal_string = '''
two \
    lines'''

date = 2025-07-09
time = 09:41:00
datetime = 2025-07-09T09:41:00.1234
datetime = 2025-07-09T09:41:00.1234Z
datetime = 2025-07-09 09:41:00.1234Z
datetime = 2025-07-09T09:41:00.1234+02:00
date . time = 2025-07-09T09:41:00.1234+02:00